### ISSUE TITLE
0.1.5 release

### ISSUE THREAD

**Issue by MassimoSporchia** [maliMirkec/hexo-cloudinary#2]
Hey there, not to apply any whatsoever pressure, but when do you think is possible to have a new release?

Thanks! 👍

**Comment by maliMirkec** [comment]
Published.

**Comment by MassimoSporchia** [comment]
Hi there, thanks, any idea when it will be available on npm too?

**Comment by maliMirkec** [comment]
I will do that first thing tomorrow morning.

**Comment by maliMirkec** [comment]
@MassimoSporchia Published on npm. 🎈
